[package]
name = "run-ciphers"
version = "1.0.0"
authors = ["Lee Bousfield <ljbousfield@gmail.com>"]

[dependencies]
libc = "0.2.15"
clap = "2.10.0"
hyper = "0.9"
rustc-serialize = "0.3"
rust-crypto = "0.2.36"
md5 = "0.2.0"
